"""create users tables

Revision ID: efcbde9ed4b1
Revises: 
Create Date: 2026-01-26 17:18:57.733916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcbde9ed4b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('phone_no', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_no_verified', sa.Boolean(), nullable=True),
    sa.Column('created_dtts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_dtts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('username'),
    schema='accounts'
    )
    op.create_index(op.f('ix_accounts_users_email'), 'users', ['email'], unique=True, schema='accounts')
    op.create_index(op.f('ix_accounts_users_id'), 'users', ['id'], unique=True, schema='accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_users_id'), table_name='users', schema='accounts')
    op.drop_index(op.f('ix_accounts_users_email'), table_name='users', schema='accounts')
    op.drop_table('users', schema='accounts')
    # ### end Alembic commands ###
